version: "3"

services:
  backend:
    restart: always
    build:
      context: ./backend
    container_name: django
    volumes:
      - backend:/backend
    command: gunicorn django-backend.wsgi --bind 0.0.0.0:8000 --timeout 600 --workers=3 --threads=3 --worker-connections=1000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - build:/frontend/build
    command: serve -s build -l 3000
    ports:
      - "3000:3000"

volumes:
  build:
  backend:
